@base_url=http://localhost:3000

### hello world
GET {{base_url}}

### エラーのテスト
GET {{base_url}}/test_error

### BabyNamesの最初の100件を出力
GET {{base_url}}/baby_names

### 1回目のレスポンスのcursorを元に、BabyNamesの次の100件を出力
GET {{base_url}}/baby_names?cursor=BGA5SSBRP4AQAAASA4EAAEEAQCAAKGQEBBSBAZBAWCXBK===

### Columnsを絞ってBabyNamesを出力
GET {{base_url}}/baby_names?colmuns=name;gender

### 男を取得
GET {{base_url}}/baby_names/gender/male

### 女を取得
GET {{base_url}}/baby_names/gender/female

### 女を2名のみ取得
GET {{base_url}}/baby_names/gender/female?maxResults=2